### ISSUE TITLE
Permission regarding stolen code / assets

### ISSUE THREAD

**Issue by rocketprogrammer** [toonisland/toonisland#7]
It is obvious that this code is decompiled utilizing EPP (Easy Python Decompiler - https://sourceforge.net/projects/easypythondecompiler/) https://github.com/toonisland/toonisland/blob/master/toontown/toonbase/ClickToStart.py#L1 from a Toontown Infinite client, but did you get permission to use their works?

Also removing credit from the people you stole from is kinda silly too - https://github.com/toonisland/toonisland/commit/266dcfa33051e51aa13132bbd17fbcb11391aee3#r109124626

![bs9lzxvj](https://user-images.githubusercontent.com/48968887/232252374-b73cc403-c937-442e-879d-f39d36b27bcb.png)

**Comment by rocketprogrammer** [comment]
https://github.com/Toontown-Open-Source-Initiative/Toontown-Magic-Word-Manager/blob/master/spellbook/ToontownMagicWordManager.py

https://github.com/toonisland/toonisland/blob/master/toontown/spellbook/TIAMagicWordManager.py

**Comment by rocketprogrammer** [comment]
@EndangeredNayla

**Comment by rocketprogrammer** [comment]
@EndangeredNayla

**Comment by EndangeredNayla** [comment]
> https://github.com/Toontown-Open-Source-Initiative/Toontown-Magic-Word-Manager/blob/master/spellbook/ToontownMagicWordManager.py
> 
> These must of been lost in translation I'm adding them back now

**Comment by rocketprogrammer** [comment]
Closing this since I believe Nayla is working to add the header on the magic word manager back, and the other stuff

**Comment by EndangeredNayla** [comment]
reopening until complete

**Comment by EndangeredNayla** [comment]
Closed via 4a0986e and a97a752
